name: Android Lint and ktlint

on:
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'

   # - name: Install ktlint
    #  run: |
     #   curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
      #  chmod +x ktlint
       # sudo mv ktlint /usr/local/bin/

   # - name: Run ktlint 
    #  run: ktlint

    - name: Run lint and ktlint
      run: |
        ./gradlew lint ktlint

    - name: Upload lint and ktlint results
      uses: actions/upload-artifact@v2
      with:
        name: lint-ktlint-results
        path: |
          app/build/reports/
          app/build/outputs/lint-results.xml
