name: Build Android Project

on:
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  build:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'

    - name: Build Android Project
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug 

    - name: Upload APKs
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/debug/
